ekf_filter_node:
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 1.0
    two_d_mode: true
    publish_tf: false

    odom_frame: "odom"
    base_link_frame: "base_link"
    world_frame: "map"

    # IMU 설정
    imu0: "/imu"
    imu0_config: [false, false, false,     # Position
                  false,  false,  false,      # Orientation (Roll, Pitch, Yaw)
                  false,  false,  false,     # Velocity (Vx, Vy)
                  true, true, true,     # Angular velocity
                  true, true, true]      # Acceleration (X, Y, Z)

    imu0_differential: false
    imu0_remove_gravitational_acceleration: true
    imu0_nodelay: false
    imu0_relative: true
    imu0_queue_size: 5
    imu0_pose_rejection_threshold: 0.8                
    imu0_twist_rejection_threshold: 0.8                
    imu0_linear_acceleration_rejection_threshold: 0.8

    # GPS 설정
    gps0: "/gps"
    gps0_config: [true,  true,  false,     # Position (x, y only)
                  false, false, false,     # Orientation
                  true, true, false,     # Velocity
                  false, false, false,     # Angular velocity
                  false, false, false]     # Acceleration

    gps0_differential: false
    gps0_relative_position: true
